# Generated by Django 4.0.3 on 2023-12-13 08:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='founder',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='founder_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
