# Generated by Django 4.0.3 on 2023-11-23 00:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='co_founder',
            field=models.ManyToManyField(related_name='co_founder_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='team',
            name='founder',
            field=models.ManyToManyField(related_name='founder_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
