# Generated by Django 4.0.3 on 2023-11-23 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='co_founder',
        ),
    ]
