# Generated by Django 4.0.3 on 2024-01-05 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(default='HQ', help_text='Enter group name (e.g. Cobra, Titan etc.)', max_length=255, null=True, unique=True),
        ),
    ]
