# Generated by Django 4.0.3 on 2023-11-23 00:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teams', '0003_remove_team_co_founder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='founder',
        ),
        migrations.AddField(
            model_name='team',
            name='founder',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='founder_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
