# Generated by Django 4.0.3 on 2024-01-10 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_alter_team_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='team_commision_precent',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Precent %'),
        ),
    ]
