# Generated by Django 4.0.3 on 2023-12-27 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='group_id',
            field=models.IntegerField(default=0),
        ),
    ]
