# Generated by Django 4.0.3 on 2024-01-01 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_profile_is_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_agent',
            field=models.BooleanField(default=True),
        ),
    ]
