# Generated by Django 4.0.3 on 2023-12-14 01:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0004_alter_profile_introducer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='introducer',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='introduced_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
