# Generated by Django 4.0.3 on 2024-01-11 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_rename_firstname_profile_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='introducer_total',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
