# Generated by Django 4.0.3 on 2023-11-20 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branchs', '0002_remove_branch_id_remove_branch_title_branch_is_hq_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='branchs.branch'),
        ),
        migrations.AddField(
            model_name='newuser',
            name='groupId',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='newuser',
            name='introducer',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newuser',
            name='serialize_user_name',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='newuser',
            name='user_view',
            field=models.IntegerField(default=0),
        ),
    ]
