# Generated by Django 4.2.7 on 2023-11-26 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branchs', '0002_alter_branch_description'),
        ('teams', '0002_initial'),
        ('users', '0002_newuser_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='branch',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='branchs.branch'),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='team',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='teams.team'),
        ),
    ]
