# Generated by Django 4.2.7 on 2023-11-26 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branchs', '0002_alter_branch_description'),
        ('users', '0003_alter_newuser_branch_alter_newuser_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='branchs.branch'),
        ),
    ]
