# Generated by Django 4.0.3 on 2023-12-28 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_newuser_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='ic_type',
            field=models.CharField(choices=[('option1', 'Option 1'), ('option2', 'Option 2'), ('option3', 'Option 3')], default='option1', max_length=10),
        ),
    ]
