# Generated by Django 4.2.7 on 2023-11-27 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branchs', '0002_alter_branch_description'),
        ('teams', '0002_initial'),
        ('users', '0004_alter_newuser_branch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newuser',
            old_name='user_name',
            new_name='username',
        ),
        migrations.AlterField(
            model_name='newuser',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='branchs.branch'),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='team',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='teams.team'),
        ),
    ]
