# Generated by Django 4.0.3 on 2023-12-28 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_newuser_ic_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='ic_no',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='ic_type',
            field=models.CharField(choices=[('NEW IC', 'newic'), ('PASSPORT / FOREIGN ID', 'passportforeign'), ('ARMY / POLICE ID', 'armypolice')], default='ID TYPE', max_length=30),
        ),
    ]
