# Generated by Django 4.0.3 on 2024-01-01 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_newuser_ic_no_alter_newuser_ic_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='is_agent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='ic_type',
            field=models.CharField(choices=[('newic', 'NEW IC'), ('passportforeign', 'PASSPORT / FOREIGN ID'), ('armypolice', 'ARMY / POLICE ID')], default='newic', max_length=30),
        ),
    ]
