# Generated by Django 4.0.3 on 2024-01-01 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_newuser_is_agent_alter_newuser_ic_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='is_agent',
            field=models.BooleanField(default=True),
        ),
    ]
