# Generated by Django 4.0.3 on 2024-01-02 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_newuser_is_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='full_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='full name'),
        ),
    ]
