# Generated by Django 4.2.7 on 2023-11-27 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_newuser_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newuser',
            name='user_name',
        ),
    ]
