# Generated by Django 4.0.3 on 2024-01-04 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_newuser_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='phone_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='full_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='full name (As Per IC)'),
        ),
    ]
