# Generated by Django 4.0.3 on 2024-01-05 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branchs', '0001_initial'),
        ('users', '0010_newuser_phone_no_alter_newuser_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='branch',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, to='branchs.branch'),
        ),
    ]
