# Generated by Django 4.0.3 on 2023-12-13 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_initial'),
        ('users', '0010_rename_serialize_user_name_newuser_serialize_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='introducer',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='team',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='teams.team'),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='user_view',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
