# Generated by Django 4.0.3 on 2024-01-05 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branchs', '0002_alter_branch_name'),
        ('users', '0011_alter_newuser_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='branch',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, to='branchs.branch'),
        ),
    ]
