# Generated by Django 4.0.3 on 2024-01-10 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_newuser_introducer'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='agent_commision_precent',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Precent %'),
        ),
    ]
