# Generated by Django 4.0.3 on 2024-01-12 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_newuser_agent_commision_precent'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='listing_admin',
            field=models.BooleanField(default=True),
        ),
    ]
