# Generated by Django 4.0.3 on 2023-12-17 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='Enter branch name (e.g. Cobra, Tycoon etc.)', max_length=255, null=True, unique=True)),
                ('location', models.CharField(default='', help_text='Enter branch name (e.g. Damansara Alif, Add Height etc.)', max_length=255)),
                ('lat', models.CharField(blank=True, max_length=20, null=True)),
                ('long', models.CharField(blank=True, max_length=20, null=True)),
                ('is_hq', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, default='', null=True)),
            ],
        ),
    ]
