# Generated by Django 4.0.3 on 2023-11-23 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('name', models.CharField(default='', help_text='Enter branch name (e.g. Damansara Alif, Add Height etc.)', max_length=255, primary_key=True, serialize=False, unique=True)),
                ('location', models.CharField(default='', max_length=255)),
                ('is_hq', models.BooleanField(default=False)),
                ('description', models.TextField()),
            ],
        ),
    ]
