# Generated by Django 4.0.3 on 2023-12-14 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branchs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='lat',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='long',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
