# Generated by Django 4.0.3 on 2023-11-20 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branchs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='id',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='title',
        ),
        migrations.AddField(
            model_name='branch',
            name='is_hq',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='branch',
            name='location',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='branch',
            name='name',
            field=models.CharField(default='', help_text='Enter branch name (e.g. Damansara Alif, Add Height etc.)', max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
