# Generated by Django 4.0.3 on 2024-01-05 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branchs', '0002_alter_branch_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='name',
            field=models.CharField(default='', help_text='Enter branch name (e.g. Cobra, Tycoon etc.)', max_length=255, null=True, unique=True),
        ),
    ]
