# Generated by Django 4.0.3 on 2023-12-14 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branchs', '0002_branch_lat_branch_long'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='location',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='branch',
            name='name',
            field=models.CharField(blank=True, default='', help_text='Enter branch name (e.g. Damansara Alif, Add Height etc.)', max_length=255, null=True, unique=True),
        ),
    ]
