# Generated by Django 4.0.3 on 2023-12-14 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branchs', '0003_alter_branch_location_alter_branch_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='location',
            field=models.CharField(default='', help_text='Enter branch name (e.g. Damansara Alif, Add Height etc.)', max_length=255),
        ),
        migrations.AlterField(
            model_name='branch',
            name='name',
            field=models.CharField(default='', help_text='Enter branch name (e.g. Cobra, Tycoon etc.)', max_length=255, null=True, unique=True),
        ),
    ]
