# Generated by Django 4.0.3 on 2024-01-10 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branchs', '0004_branch_branch_commision_precent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='branch_commision_precent',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Precent %'),
        ),
    ]
