# Generated by Django 4.0.3 on 2023-12-17 13:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import inventory.models
import location_field.models.plain


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branchs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=150)),
                ('location', location_field.models.plain.PlainLocationField(blank=True, max_length=63, null=True)),
                ('propertyTitle', models.CharField(choices=[('Strata', 'Strata'), ('Land', 'Land')], default='Strata', max_length=50)),
                ('saleType', models.CharField(choices=[('For Sale', 'For Sale'), ('For Rent', 'For Rent')], default='For Sale', max_length=50)),
                ('rentalDeposit', models.CharField(max_length=50, null=True, verbose_name='Rental Deposit')),
                ('tenure', models.BooleanField(default=False)),
                ('slug', models.CharField(max_length=200, unique=True)),
                ('title', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('zipcode', models.CharField(max_length=15)),
                ('description', models.TextField(blank=True)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9, null=True, verbose_name='Latitude')),
                ('lon', models.DecimalField(decimal_places=6, max_digits=9, null=True, verbose_name='Longitude')),
                ('price', models.IntegerField()),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.DecimalField(decimal_places=1, max_digits=2)),
                ('floorRange', models.IntegerField(blank=True, null=True)),
                ('size', models.IntegerField(blank=True, null=True)),
                ('furnishing', models.CharField(choices=[('Fully furnish', 'Fully Furnish'), ('Partial', 'Partial Furnish'), ('None', 'None')], default='None', max_length=50)),
                ('amenities', models.CharField(max_length=200, null=True)),
                ('carpark', models.IntegerField()),
                ('otherInfo', models.CharField(max_length=255, null=True)),
                ('featureImage', models.ImageField(blank=True, null=True, upload_to=inventory.models.get_upload_path, verbose_name='Cover Image')),
                ('photo_1', models.ImageField(blank=True, null=True, upload_to=inventory.models.get_upload_path)),
                ('photo_2', models.ImageField(blank=True, null=True, upload_to=inventory.models.get_upload_path)),
                ('photo_3', models.ImageField(blank=True, null=True, upload_to=inventory.models.get_upload_path)),
                ('photo_4', models.ImageField(blank=True, null=True, upload_to=inventory.models.get_upload_path)),
                ('photo_5', models.ImageField(blank=True, null=True, upload_to=inventory.models.get_upload_path)),
                ('photo_6', models.ImageField(blank=True, null=True, upload_to=inventory.models.get_upload_path)),
                ('photo_7', models.ImageField(blank=True, null=True, upload_to=inventory.models.get_upload_path)),
                ('photo_8', models.ImageField(blank=True, null=True, upload_to=inventory.models.get_upload_path)),
                ('photo_9', models.ImageField(blank=True, null=True, upload_to=inventory.models.get_upload_path)),
                ('photo_10', models.ImageField(blank=True, null=True, upload_to=inventory.models.get_upload_path)),
                ('video', models.URLField(null=True)),
                ('is_published', models.BooleanField(default=True)),
                ('status', models.BooleanField(default=True)),
                ('inventory_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('view_count', models.IntegerField(default=0)),
                ('branch', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='branchs.branch')),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='category', to='inventory.category')),
                ('propertyType', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='inventory.propertytype')),
            ],
        ),
    ]
