# Generated by Django 4.0.3 on 2023-12-26 15:35

from django.db import migrations, models
import inventory.models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='featureImage',
            field=models.ImageField(blank=True, null=True, upload_to=inventory.models.get_upload_path, verbose_name='Featured Image'),
        ),
    ]
