# Generated by Django 4.0.3 on 2023-11-26 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branchs', '0002_alter_branch_description'),
        ('inventory', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='branchs.branch'),
        ),
    ]
