# Generated by Django 4.0.3 on 2024-01-05 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branchs', '0003_alter_branch_name'),
        ('inventory', '0003_alter_inventory_featureimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='branch',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='branchs.branch'),
        ),
    ]
