# Generated by Django 4.0.3 on 2024-01-12 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_inventory_branch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='lon',
            new_name='long',
        ),
    ]
