# Generated by Django 4.0.3 on 2024-01-12 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_rename_lon_inventory_long'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='lat',
            field=models.DecimalField(decimal_places=6, default=1.515518, max_digits=9, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='long',
            field=models.DecimalField(decimal_places=6, default=103.72535, max_digits=9, null=True, verbose_name='Longitude'),
        ),
    ]
