# Generated by Django 4.0.3 on 2024-01-12 21:58

from django.db import migrations, models
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_inventory_lat_alter_inventory_long'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='location_lat_long',
            field=location_field.models.plain.PlainLocationField(blank=True, max_length=63, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
