# Generated by Django 4.0.3 on 2024-01-13 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_inventory_location_lat_long_alter_inventory_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='status',
            new_name='is_available',
        ),
        migrations.AlterField(
            model_name='inventory',
            name='carpark',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=20, default=1.515518, max_digits=100, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='long',
            field=models.DecimalField(blank=True, decimal_places=20, default=103.72535, max_digits=100, null=True, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='video',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='zipcode',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
