# Generated by Django 4.0.3 on 2024-01-13 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_alter_inventory_lat_alter_inventory_long'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='is_available',
            new_name='status',
        ),
    ]
