# Generated by Django 4.0.3 on 2024-01-13 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_rename_is_available_inventory_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=20, default=1.515518, max_digits=50, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='long',
            field=models.DecimalField(blank=True, decimal_places=20, default=103.72535, max_digits=50, null=True, verbose_name='Longitude'),
        ),
    ]
