# Generated by Django 4.0.3 on 2024-01-16 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_alter_inventory_amenities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='rentalDeposit',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Rental Deposit'),
        ),
    ]
