# Generated by Django 4.0.3 on 2023-11-15 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Task',
            new_name='Master',
        ),
    ]
