# Generated by Django 4.0.3 on 2023-11-15 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0002_rename_task_master'),
    ]

    operations = [
        migrations.RenameField(
            model_name='master',
            old_name='title',
            new_name='name',
        ),
        migrations.AddField(
            model_name='master',
            name='is_hq',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='master',
            name='location',
            field=models.TextField(default=''),
        ),
    ]
