# Generated by Django 4.0.3 on 2023-11-15 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0003_rename_title_master_name_master_is_hq_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='location',
            field=models.CharField(default='', max_length=255),
        ),
    ]
