# Generated by Django 4.0.3 on 2023-11-16 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('branch', '0004_alter_master_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='groups',
            field=models.ManyToManyField(to='auth.group'),
        ),
        migrations.AddField(
            model_name='master',
            name='user_permissions',
            field=models.ManyToManyField(to='auth.permission'),
        ),
    ]
