# Generated by Django 4.0.3 on 2023-11-16 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0005_master_groups_master_user_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
