# Generated by Django 4.0.3 on 2023-11-16 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0007_remove_master_groups_remove_master_user_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='master',
            name='id',
        ),
        migrations.AlterField(
            model_name='master',
            name='name',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
